M48
; DRILL file {KiCad 6.0.2+dfsg-1} date vr 01 sep 2023 16:32:18
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-01T16:32:18+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X88.0Y-53.0
X88.75Y-127.25
X153.75Y-52.75
X153.75Y-127.25
T0
M30
